(defview return405 env (:foo :test) ()
  (format t "test message~%env: ~W~%" env)
  (setf (status-code env) 405)
  (setf (gethash :content-type (response-headers env)) "text/html; charset=UTF-8")
  (setf (cl-who:html-mode) :html5)
  (cl-who:with-html-output-to-string (s nil :prologue t :indent t)
	  (:html (:head (:title "braculon:405"))
		 (:body
		  (:h1 "405")
		  (:p "Method Not Allowed")))))
